[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 