[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

# Next.js specific configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Static files should not be redirected
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200

# Security headers (fix X-Frame-Options warning)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"

# Web Manifest
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json" 